- name: Clone and copy files to /var/www/html
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Installing git
      apt:
        name: git

    - name: Installing Nginx
      apt:
        name: nginx

    - name: Starting nginx
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Clone Git repository
      git:
        repo: https://github.com/Simrankhott/ansible-web.git
        dest: /tmp/simmu

    - name: Copy files to /var/www/html
      copy:
        src: /tmp/simmu
        dest: /var/www/html
        remote_src: true

